Story7/urls.py
from django.urls import include, path

from . import views

app_name = 'Story7'

urlpatterns = [
    path('', views.index, name='index'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('experience', views.experience, name="experience"), 
    path('contact', views.contact, name='contact'),
    path('random-facts', views.randomFacts, name='randomFacts'),
    path('matakuliah', views.formSave, name='matakuliah'),
    path('detailMataKuliah/<int:matkul_id>', views.detailMataKuliah, name='detailMataKuliah'),
    path('delete/<int:matkul_id>', views.formDelete, name='formDelete'),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('event/', include('story6.urls')),
    path('accordion/', include('Story7.urls')),
]

story6/urls.py
from django.urls import include, path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.indexEvent, name='indexEvent'), 
    path('addEvent/', views.addEvent, name='addEvent'),
    path('addMember/<str:id>', views.addMember, name='addMember'),
    path('deleteMember/<str:id>', views.deleteMember, name='deleteMember'),
]

Story7/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django import forms

class Matkul(models.Model):
    name = models.CharField(max_length=225)
    dosen = models.CharField(max_length=225)
    sks = models.IntegerField(blank=False)
    deskripsi = models.CharField(max_length=225)
    semthn = models.CharField(max_length=225)
    kelas = models.CharField(max_length=225)

    def __str__(self):
        return '%s' % self.name

story1/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Member(models.Model):
    name = models.CharField(max_length=50)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from .models import Matkul

class TheForm(ModelForm):
    class Meta:
        model = Matkul
        fields = '__all__'

story6/forms.py
from django import forms
from .models import Event, Member

class CreateEvent(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name']

class CreateMember(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name', 'event']

Story7/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import TheForm
from .models import Matkul


def home(request):
    return render(request, 'main/home.html')

def experience(request):
    return render(request, 'main/experience.html')

def contact(request):
    return render(request, 'main/contact.html')

def randomFacts(request):
    return render(request, 'main/randomFacts.html')

def MatkulViews(request):
    matkul_items = Matkul.objects.all()
    return render(request, 'main/matkulForm.html', {'matkul' : matkul_items})

def formSave(request):
    if request.method == 'POST':
        form = TheForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            return HttpResponseRedirect('matakuliah')

    form = TheForm()
    matkul_items = Matkul.objects.all()
    return render(request, 'main/matkulForm.html', {'form' : form, 'matkul' : matkul_items})

def formDelete(request, matkul_id):
    matkul = Matkul.objects.filter(id = matkul_id)
    matkul.delete()

    return redirect('main:matakuliah')


def detailMataKuliah(request, matkul_id):
    matkul= Matkul.objects.get(id = matkul_id)
    print(matkul.name)
    return render(request, 'main/detailMatkul.html', {'matkul' : matkul})

story1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

story6/views.py
from django.shortcuts import render, redirect
from .models import Event, Member
from .forms import CreateEvent, CreateMember

# Create your views here.

def indexEvent(request):
    event = Event.objects.all()
    member = Member.objects.all()
    return render(request, 'event.html', {'event' : event, "member" : member})

def addEvent(request):
    if request.method == 'POST':
        form = CreateEvent(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story6:indexEvent')
    return render(request, 'addEvent.html')

def addMember(request, id = 0):
    id = int(id)
    event = Event.objects.get(id=id)
    if request.method == 'POST':
        id = request.POST['eventId']
        name = request.POST['name']
        event = Event.objects.get(id=id)
        data = {'name' : name, 'event' : event}
        form = CreateMember(data=data)
        if form.is_valid():
            form.save()
            return redirect('story6:indexEvent')
    return render(request, 'addMember.html', {'event' : event})

def deleteMember(request, id):
    id = int(id)
    member = Member.objects.get(id=id)
    member.delete()
    return redirect('story6:indexEvent')

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-5 socmed-col">
            <div class="row justify-content-center align-content-center">
                <h3 class="" id="uppersocmed">feel free to<strong> stop by</strong></br>and<strong> say hi!</strong></h3>
            </div>
            <div class="row justify-content-center">
                <a href="https://instagram.com/rizmachaeranii" target="_blank">
                    <img src="{%static 'contact/instagram.svg'%}" alt="" class="socmed">
                </a>
                <a href="https://twitter.com/rizmachaeranii" target="_blank">
                    <img src="{%static 'contact/twitter.svg'%}" alt="" class="socmed">
                </a>
            </div>
            <div class="row justify-content-center">
                <a href="https://www.linkedin.com/in/rizma-chaerani-heidy-p-149359194/" target="_blank">
                    <img src="{%static 'contact/linkedin.svg'%}" alt="" class="socmed">
                </a>
                <address>
                    <a href="mailto:rizmachaerani@gmail.com">
                        <img src="{%static 'contact/Mail.svg'%}" alt="" class="socmed pt-2">
                    </a>
                </address>
            </div>
            <div class="row justify-content-center">
                <h2 class="text text-center socmed-text" id="lowersocmed">🙌</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center text-center pt-5">
        <h5 id="contact-bottom">also, kindly check my projects<br><a href="{% url 'story1:index'%}">
            <strong id="strong-text-2">Story 1</strong></a><br><a href="{% url 'main:matakuliah'%}">
            <strong id="strong-text-2">Story 5</strong></a><br>
            thank you! xx</h5>    
    </div>
</div>
{% endblock content %}

main/templates/main/experience.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section id="experience-section">
    <div class="container experience-section justify-content-md-center mb-5">
        <div class="row">
              <div class="col-lg-6 col-md-12 pt-3 pl-5">
                  <div class="row">
                      <a href="{% url 'main:randomFacts'%}">
                          <h2 id="experience"><strong>Experience</strong></h2>
                      </a>
                  </div>
                  <div class="row">
                      <table>
                          <tr>
                              <td>
                                  <h5 class="pt-3"><strong>Asia Kakehashi Project</strong></h5>
                                  <h6>Returnee</h6>
                                  <p>2018 - 2019</p>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <h5><strong>COMPFEST12</strong></h5>
                                  <h6>Staff of Startup Academy</h6>
                                  <p>2020</p>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <h5><strong>TOSKA UI 2020</strong></h5>
                                  <h6>Staff of Ticketing</h6>
                                  <p>2020</p>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <h5><strong>BEM Fasilkom UI</strong></h5>
                                  <h6>Staff of Business and Partnership Bureau</h6>
                                  <p>2020</p>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <h5><strong>Keluarga Mahasiswa Sriwijaya UI</strong></h5>
                                  <h6>Staff of Internal Development</h6>
                                  <p>2020</p>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <h5><strong>TOSKA UI 2021</strong></h5>
                                  <h6>PIC  of Ticketing</h6>
                                  <p>2021</p>
                              </td>
                          </tr>
                          <tr>
                              <td>
                                  <h5><strong>Bina Antarbudaya</strong></h5>
                                  <h6>Volunteer</h6>
                                  <p>2016 - Present</p>
                              </td>
                          </tr>
                      </table>
                  </div>
              </div>
              <div class="col pt-3 pl-5" id="right-side">
                  <div class="row">
                      <h2 id="edu"><strong>Education</strong></h2><br>
                  </div>
                  <div class="row">
                      <table class="education-table">
                          <tr>
                              <td class="image logo-image text-center"><img src="{%static 'aboutMe/ui.svg'%}" id="ui"></td>
                              <td class="table-text pt-3 pl-3">
                                  <h5><strong>University of Indonesia</strong></h5>
                                  <h6>Information Systems</h6>
                                  <p>2019 - Present</p>
                              </td>
                          </tr>
                          <tr>
                              <td class="image text-center"><img src="{%static 'aboutMe/sma17.svg'%}" id="sma17"></td>
                              <td class="table-text pt-3 pl-3">
                                  <h5><strong>SMA Plus Negeri 17 Palembang</strong></h5>
                                  <p>2016 - 2019</p>
                              </td>
                          </tr>
                          <tr>
                              <td class="image logo-image text-center"><img src="{%static 'aboutMe/smp9.svg'%}" id="smp9"></td>
                              <td class="table-text pt-3 pl-3">
                                  <h5><strong>SMP Negeri 9 Palembang</strong></h5>
                                  <p>2013 - 2016</p>
                              </td>
                          </tr>
                      </table>
                  </div>
                  <div class="row button-row mb-5 d-flex justify-content-center justify-content-md-start m-0">
                      <a href="{% url 'main:contact'%}">
                          <button type="button" class="btn btn-primary button" id="contact-button"><h4 class="btn-text">let's get in touch</h4></button>
                        </a>
                  </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section id="section1">
      <div class="container">
        <img src="{% static 'home/blob1.svg'%}" id="blob" alt="">
        <div id="helloname">
          <h1 id="name"><span id="hello">Hello👋</span><br>Rizma's here!</h1>
        </div>
        <div id="gettoknowmorediv">
          <a href="{% url 'main:home'%}#section2">
          <h4 class="text" id="gettoknowmore">get to know more 👇</h4>
          </a>
        </div>
      </div>
    </section>

    <section id="section2" class="about-me">
      <div class="container">
          <div class="row about-me-row text-center justify-content-sm-center align-self-sm-center">
              <div class="col-lg-4">
                  <img class="img-fluid" src="{% static 'aboutMe/image2.svg'%}" id="image" alt="Responsive Image">
              </div>
              <div class="col-lg-8">
                  <div class="row">
                      <p class="pt-2" id="about-me-text"><span id="about-me-title">About Me<br></span> My name is <strong>Rizma Chaerani (1906299111)</strong> and I'm one of batch <strong>2019</strong> students majoring in <strong>Information Systems</strong> in the <strong>Faculty of Computer Science, Universitas Indonesia</strong>. During the pandemic, I have developed some new hobbies, including <strong>brewing coffee and deepening my knowledge about the science behind coffee brewing</strong>. I'm currently attending Web Design and Programming class and this website is one of the assignments I received. </p>
                  </div>
                  <div class="d-flex justify-content-center justify-content-lg-start m-0">
                    <a href="{%url 'main:experience'%}">
                      <button type="button" class="btn btn-danger button img-fluid" alt="Responsive Image"><h4 class="btn-text">education and experience</h4></button>
                    </a>
                  </div>
              </div>
          </div>
      </div>
    </section>
{% endblock content %}

main/templates/main/matkulForm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row text-center justify-content-center">
        <h3>Catatan Mata Kuliah</h3>
    </div>
    <div class="d-flex justify-content-center">
        <form  method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td id="namaMatkul">Mata Kuliah: </td>
                    <td class="pl-3">: {{ form.name }}</td>
                </tr>
                <tr>
                    <td id="dosen">Pengajar: </td>
                    <td class="pl-3">: {{ form.dosen }}</td>
                </tr>
                <tr>
                    <td id="sks">Jumlah SKS: </td>
                    <td class="pl-3">: {{ form.sks }}</td>
                </tr>
                <tr>
                    <td id="deskripsi">Deskripsi: </td>
                    <td class="pl-3">: {{ form.deskripsi }}</td>
                </tr>
                <tr>
                    <td id="semthn">Tahun: </td>
                    <td class="pl-3">: {{ form.semthn }}</td>
                </tr>
                <tr>
                    <td id="kelas">Ruang Kelas: </td>
                    <td class="pl-3">: {{ form.kelas }}</td>
                </tr>
                <tr>
                    <td class="text-right" colspan="2">
                        <input type="submit" value="Add"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <div class="row justify-content-center">
        <h3>List Mata Kuliah</h3>
    </div>
    <div class="row justify-content-center">
        <table>
            {% for matkul_item in matkul %}
            <tr>
                <td><a href="{% url 'main:detailMataKuliah' matkul_item.id %}" style="color: white;">{{ matkul_item.name }}</a></td>
                <td class="pl-5"><a href="{% url 'main:formDelete' matkul_item.id %}"> Delete </a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

story1/templates/home/index.html
<!doctype html>
<html lang="en">

    {% load static %}


  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/story1.css' %}"/>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">

    <title>Hello, world!</title>
  </head>
  <body>
    <section id="firstpart">
        <div class="container">
            <div class="row justify-content-center first-part first-text">
                <h2 class="text" id="hey">Hello👋</h2>
            </div>
            <div class="row justify-content-center first-part">
                <h1 class="text" id="itsrizma"><strong>Rizma</strong>'s here!</h1>
            </div>
            <div class="row justify-content-center">
                <a href="#about-me">
                    <h4 class="text" id="gettoknowmore"><Strong>get to know more about me</Strong></h4>
                    <h4 class="text-center">👇</h4>
                </a>
            </div>
        </div>
    </section>

    <section id="secondpart">
        <div class="container">
            <div class="row about-me" id="about-me">
                <div class="col-lg-5 col-md-8 text-center justify-content-sm-center">
                    <img src="{% static 'images/mypicture.svg' %}" class="img-fluid" alt="Responsive image" id="my-image">
                </div>
                <div class="col-lg-7 col-md-8">
                    <div class="row text about-me-text">
                        <p>My name is <strong>Rizma Chaerani (1906299111)</strong> and I'm one of batch <strong>2019</strong> students majoring in <strong>Information Systems</strong> in the <strong>Faculty of Computer Science, Universitas Indonesia</strong>. During the pandemic, I have developed some new hobbies, including <strong>brewing coffee and deepening my knowledge about the science behind coffee brewing</strong>. I'm currently attending Web Design and Programming class and this website is one of the assignments I received. </p>
                    </div>
                </div>
            </div>

            <div class="row last-row">
                <div class="col-lg-7">
                    <div class="card edu-card">
                        <div class="card-body">
                            <h3 class="text text-center edu-text"><i><strong>Education</strong></i></h3>
                            <table class="text education-table">
                                <tr>
                                    <td class="image text-center"><img src="{% static 'images/ui.svg' %}" class="logo-image" id="ui"></td>
                                    <td class="table-text pt-3">
                                        <h5><strong>University of Indonesia</strong></h5>
                                        <h6>Information Systems</h6>
                                        <p>2019 - Present</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="image text-center"><img src="{% static 'images/sma17.svg' %}" id="sma17"></td>
                                    <td class="table-text pt-3">
                                        <h5><strong>SMA Plus Negeri 17 Palembang</strong></h5>
                                        <p>2016 - 2019</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="image text-center"><img src="{% static 'images/smp9.svg' %}" class="logo-image" id="smp9"></td>
                                    <td class="table-text pt-3">
                                        <h5><strong>SMP Negeri 9 Palembang</strong></h5>
                                        <p>2013 - 2016</p>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                    <div class="col-lg-5 socmed-col">
                        <div class="row justify-content-center">
                            <h3 class="text text-center socmed-text" id="uppersocmed">feel free to<strong> stop by</strong></br>and<strong> say hi!</strong></h3>
                        </div>
                        <div class="row justify-content-center">
                            <a href="https://instagram.com/rizmachaeranii" target="_blank">
                                <img src="{% static 'images/instagram.svg' %}" alt="" class="socmed">
                            </a>
                            <a href="https://twitter.com/rizmachaeranii" target="_blank">
                                <img src="{% static 'images/twitter.svg' %}" alt="" class="socmed">
                            </a>
                        </div>
                        <div class="row justify-content-center">
                            <a href="https://www.linkedin.com/in/rizma-chaerani-heidy-p-149359194/" target="_blank">
                                <img src="{% static 'images/linkedin.svg' %}" alt="" class="socmed">
                            </a>
                            <a href="https://wa.me/6282281019116">
                                <img src="{% static 'images/whatsapp.svg' %}" alt="" class="socmed">
                            </a>
                        </div>
                        <div class="row justify-content-center">
                            <h2 class="text text-center socmed-text" id="lowersocmed">🙌</h2>
                        </div>
                    </div>
                </div>
            </div>
                <div class="d-flex justify-content-center mb-5">
                    <a href="{% url 'main:home'%}">
                        <button type="button" class="btn btn-success button">STORY 4</button>
                    </a>
                </div>
        </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

story6/templates/event.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="courses">
        <div class="header"><h1>Event List</h1></div>
        <button type="button" class="btn btn-primary btn-lg my-2" onclick="location.href='{% url 'story6:addEvent' %}'">Add Event</button>
        {% if event is not none %}
            <div class="table">
                {% for i in event %}
                <div class="card">
                    <h5 class="card-header">{{ i.name }}</h5>
                    <div class="card-body">
                    <h5 class="card-title">Member :</h5>
                    <ul class="list-group">
                    {% for j in member %}
                        {% if j.event == i %}
                            <li class="list-group-item d-flex justify-content-between">
                                <span>{{j.name}}</span>
                                <a class="material-icons text-danger text-decoration-none" href="{% url 'story6:deleteMember' j.id %}">delete</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                    <button type="button" class="btn btn-info my-2" onclick="location.href='{% url 'story6:addMember' id=i.id %}'">Add Member</button>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
        <h1>Event Not Exist</h1>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- My Font -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <title>Rizma C</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom navbar-fixed-top">
      <div class="container">
          <h3 class="logo">RIZMA C</h3>
          <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home' %}">HOME <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home'%}#section2">ABOUT ME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:contact'%}">CONTACT</a>
              </li>
            </ul>
          </div>
      </div>
    </nav>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
  {% block content %}
  {% endblock content %}
</html>

templates/base2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="{%static 'script.js'%}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">


    <!-- My Font -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <!-- <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

    <title>Rizma C</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom navbar-fixed-top">
      <div class="container">
          <h3 class="logo">RIZMA C</h3>
          <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home' %}">HOME <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home'%}#section2">ABOUT ME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:contact'%}">CONTACT</a>
              </li>
            </ul>
          </div>
      </div>
    </nav>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> -->
  </body>
  {% block content %}
  {% endblock content %}
</html>